### PR TITLE
babette is the wrapper around beautier, beastier and tracerer

### PR DESCRIPTION
**Pull request by richelbilderbeek**
Hi, 

I am the maintainer of the beautier, beastier, tracerer and babette R packages and found a mistake, which was probably a copy-paste error. Here I fix it :-)

Thanks and cheers, Richel Bilderbeek

### CODE REVIEW

**Comment by willgearty** [comment]
Thanks for the correction @richelbilderbeek. It looks like babette is no longer on CRAN. Do you have any plans to restore it to CRAN?

**Comment by willgearty** [comment]
@richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
I have gotten all of babette's prerequisites to be back on CRAN again, just resubmitted babette.

Due to holidays, I'd say Monday 1st of July is a reasonable deadline, but it is hard to predict when CRAN maintainers take a holiday from my side :+1:

**Comment by richelbilderbeek** [comment]
@willgearty it is fixed! Thanks for letting me know https://cran.r-project.org/package=babette was down :+1:

**Comment by willgearty** [comment]
Great, to hear! Merging!

**Pull request merged**
