### PR TITLE
GitHub action: Validate task view

### PR DESCRIPTION
**Pull request by ms609**
Following discussion in #3, this GitHub action automatically checks whether pull requests are valid.

The action:

- [x] Succeeds when `Phylogenetics.md` passes validation tests. (Example: This PR)
- [x] Fails when document does not render due to syntax error: [Example](https://github.com/cran-task-views/Phylogenetics/actions/runs/3378128897/jobs/5607926978)
- [x] Fails when bad CRAN packages are found. [Example](https://github.com/cran-task-views/Phylogenetics/actions/runs/3378533327/jobs/5608860651)
- [x] Fails when links cannot be validated. [Example](https://github.com/cran-task-views/Phylogenetics/actions/runs/3378407818/jobs/5608566271)

By default, the action will run on all pull requests, and denote its status.
It is possible (but not necessary) to prevent pull requests from being pulled when the action fails.  This may be undesirable in this context, as it is possible to experience false negatives, for example if a server error means that links to external sites cannot be validated.

### CODE REVIEW

**Comment by zeileis** [comment]
It is not necessary to require that there are no archived packages in the task view. For a certain grace period, it is ok to keep archived packages in the task view. For PRs it might be a reasonable restriction to require that they don't lead to more archived packages than in the task view version that they started out from.

**Comment by ms609** [comment]
Thanks for the suggestion; I've modified the requirement to fail only if a PR introduces archived packages that are not presently on the `main` branch.

**Comment by willgearty** [comment]
This is great, thanks @ms609! Would it be possible to run all checks, even when an earlier one fails? That way you would be able to see everything that is wrong instead of piecemeal fixing the problems.

**Comment by ms609** [comment]
I've added an "always run" command to the final block.  But  if there's a syntax error, I don't think the task view will be parsed, so the checks will not be able to extract  packages - thus the setps will fail without returning useful information

**Comment by tuxette** [comment]
Thanks @ms609 : very useful!

**Comment by ms609** [comment]
Splendid, many thanks for your help with the implementation!  I've updated this PR to use the ctv action. 

Just a thought (which should have occurred to me sooner, sorry): would it be worth naming the `action` folder something more descriptive, such as `validate-ctv`, in case other actions are proposed for different purposes in the future?  At present, it is not entirely clear to me as a reader of a yaml file what I can expect the line `uses: cran-task-views/ctv/action` to accomplish.

**Comment by ms609** [comment]
Great! I've updated the action script here, so this PR should be ready to merge.

**Comment by willgearty** [comment]
Thanks for all of the work on this @ms609 and @tuxette!

**Pull request merged**
