### PR TITLE
some suggestions re:phytools

### PR DESCRIPTION
**Pull request by liamrevell**

### CODE REVIEW

**Review by hlapp — APPROVED** [review]
Thanks @liamrevell, LGTM 👍

**Comment by zeileis** [comment]
Before merging please check `ctv::ctv2html("Phylogenetics.md")` and `ctv::check_ctv_packages("Phylogenetics.md")` to make sure that everything is in order. In this commit some `r pkg(...)` were lacking the closing backtick and hence `ctv2html()` did not work.

Fixed now (with a few other minor improvements).

**Comment by willgearty** [comment]
Thanks @zeileis! Is there a GitHub action we could set up to automatically run those checks?

**Comment by zeileis** [comment]
No, not yet. It's on the wish-list but my GitHub skills are not sufficient, yet, for setting something like that up.

**Comment by eddelbuettel** [comment]
If I may: I would recommend against.  You can run any shell script snippet at GitHub Actions too, and those are portable to another provider if, $deity forbid, we have to do another dance like the Travis -> GitHub migration.  I keep my setup minimally tied to a provider, and what I use I documented at [r-ci](https://eddelbuettel.github.io/r-ci) to be useable at (three, at least) different backends.

But as always, _different strokes for different folks_, and these just happen to be the $0.02 that work for me.

**Comment by zeileis** [comment]
Can you suggest a concrete r-ci-based setup that CRAN Task View maintainers could adopt for automating checks of their task view files?

**Comment by eddelbuettel** [comment]
I can only point to `r-ci` as something that a) runs in standard Ubuntu and b) pulls in what it needs to do its task: run `R CMD check` reliably without extra effort in a fully automated fashion in minimal time (now taking advantage of `r2u`).  If someone (@willgearty, say) wants to use that as a model to enable pre-commit checks I could look over his shoulder.

Per GitHub's count I am at 446 repositories.  None of those have pre-commit hooks (as far as I know, I may have inherited one or two on forked repos; I surely haven't added anything myself to that effect).  But the beauty of this model is that anybody can  hook just about anything executable in there given the generality of, say, a `ubuntu-latest` platform.

**Comment by ms609** [comment]
I've constructed a GitHub action that runs `ctv::ctv2html("Phylogenetics.md")` and `ctv::check_ctv_packages("Phylogenetics.md")`, and additional checks links to external repositories (e.g. GitHub / Bioconductor).  Feel free to comment at #4.

**Comment by tuxette** [comment]
I'm all for propagating this for the other TV. @zeileis : I could test it on MissingData TV and write a documentation to explain maintainers how to do that for their repositories. What do you think?

**Comment by zeileis** [comment]
Sounds good. I'm not competent enough, though, to comment on the way the GitHub action was implemented now and whether it should be improved/adapted further.

**Comment by tuxette** [comment]
I'll try to do that tomorrow (if my work load allows it) and I'll give you a personal feedback (even though I'm probably also not competent enough!).

**Comment by ms609** [comment]
There are probably a few changes that could simplify the use of the workflow on other Task Views (e.g. replacing the hard-coded `Phylogenetics.md` with a variable that could be defined once – or perhaps even making a standalone script that can be loaded with `uses:`) – if the goal is to have a widely used workflow, it may be worth having a standalone repo so that improvements can propagate, rather than relying on copying & pasting.

**Comment by ms609** [comment]
I've now created a [template workflow](https://github.com/ms609/actions/tree/main/validate-ctv) that should be easy to use on any cran task view repository.  This will allow future improvements to benefit all task views using the workflow.  Feedback is welcome – either here, or perhaps better, by [filing an issue](https://github.com/ms609/actions/issues) in that repo.

**Comment by hlapp** [comment]
Super cool, thanks @ms609 and @tuxette 🎉

**Comment by tuxette** [comment]
Hi @ms609 : I've tested your proposal (thanks a lot!) and also discuss it a bit with @zeileis .
1. as it is, it is simple to use and works perfectly (except that, unless I am mistaken, the file at https://github.com/ms609/actions/tree/main/validate-ctv should be copied in `user/TaskViewName/.github/workflows/validate-ctv.yml` and not in `user/TaskViewName/.github/actions/validate-ctv.yml`)
2. I think that we can avoid completely using the reference to `<TaskViewName>`. I've also tested that in https://github.com/cran-task-views/MissingData/blob/main/.github/workflows/validate-ctv.yml that uses this slightly modified version of your proposal: https://github.com/tuxette/actions/blob/main/action.yml
3. If you don't mind, it would be clearer for users that we install these two files in the CTV repository: what do you think? Also (I will have to check it), it could probably be installed directly with no action from the user with `usethis::use_github_action` which would even be simpler.

**Comment by ms609** [comment]
Hi @tuxette , thanks for these suggestions!

1. correct – now fixed!
2. a.  `     - '<TaskViewName>.md'` in paths allows the task view to run only when the main task view file is edited, conserving GHA resources – and thus meaning that runs aren't queued unnecessarily.  It can be dispensed with in the interests of simplicity.
 b.   `task-view: <TaskViewName>` -- reading this from the context is a great idea
3.  a. moving the files from `ms609/actions/` to `cran-task-views/actions` would be eminently sensible
 b. It looks like `use_github_action` just copies an existing `.yml` file to the appropriate location – which would require the removal of `<TasKViewName>`.

What are the next steps?

**Comment by tuxette** [comment]
Hi @ms609 ! Thanks for the comments.
I don't know how to balance your remarks in 2a with 3b. For me, it would be easier to just mention the user to install the TV with `use_github_action` but I agree that 2a is an important point. @zeileis @ms609 : your thoughts?
As for the transition of the action from your repository to CTV, I'm all for it once we have agreed on the previous question and on which recommendations to make to users. I could take care of that unless @zeileis wants to handle it.

**Comment by zeileis** [comment]
I agree with both of you that saving resources (2a) is an important point.
I'm happy if you handle the next steps, Nathalie @tuxette .

Thanks to both of you!

**Comment by tuxette** [comment]
If that works for you, @ms609 and @zeileis , I'll create a directory `actions` in the `ctv` repository and pushed the corrected versions of `validate-ctv.yml` and of the action (keeping the manual installation, then, to avoid unnecessary checks). I could also add a section at the end of `Documentation.md` explaining how to use this action (but not making this use mandatory).

**Comment by zeileis** [comment]
Great, thanks, sounds all good to me.

**Comment by tuxette** [comment]
@zeileis : I think I'm done. I've sent a pull request to the main branch (from a branch named "action") for you to review and approve (note that links and the action will be functional only after the pull request is performed). I don't know if we should acknowledge Martin for its initial contribution (and where) so I let you handle that. And again, @ms609 : thanks a lot!

**Comment by zeileis** [comment]
Is there a canonical place where in a GitHub Action .yml you would typically indicate authors/contributions? If so, we should mention the initiative along with Martin there.

**Pull request merged**
